server:
  port: 8060

spring:
  application:
    name: micro-geteway-zuul

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8000/eureka/
    instance:
      # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
      prefer-ip-address: true

# 配置自定义路由 serviceId = 指定路径
zuul:
  routes:
    micro-user: /wuzx/user/**

  # 忽略服务 使用'*'可忽略所有微服务
  ignored-services: microservice-provider-user,microservice-consumer-movie

logging:
  level:
    com.netflix: DEBUG

