server:
  port: 8050

spring:
  application:
    name: micro-hystrix
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8000/eureka/
    instance:
      # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
      prefer-ip-address: true

# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

